---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-service
  namespace: arc-aks-helloworld
spec:
  selector:
    app: aks-helloworld
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
